CREATE TABLE `FOODS` (
  `id` INTEGER PRIMARY KEY AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  `protein` INTEGER NOT NULL,
  `carbohydrates` INTEGER NOT NULL,
  `fat` INTEGER NOT NULL
);

CREATE TABLE `INTAKE` (
  `date` DATE PRIMARY KEY NOT NULL,
  `id` INTEGER AUTO_INCREMENT,
  `food_id` INTEGER NOT NULL
);

ALTER TABLE `INTAKE` ADD FOREIGN KEY (`food_id`) REFERENCES `FOODS` (`id`);
